export const ProjectData = [
  {
    id: 2,
    src: 'images/advertising/bmw_ad.png',
    alt: 'BMW Ad',
    brand: 'BMW',
    desc: "'Don't text and drive'",
    date: 'Published/Aired: June 2020',
    award_title: 'Auto & Auto Services Advertising, Media & PR 2021',
    award_src: 'American Advertising Award Winner',
  },
  {
    id: 0,
    src: 'images/advertising/indian_river_ad.png',
    alt: 'Indian River Select',
    brand: 'Indian River Select',
    desc: "'Get ready to fight'",
    date: 'Published/Aired: August 2019',
    award_title: 'Best Art Direction Advertising, Media & PR 2021',
    award: 'Webby Award Winner',
  },

  {
    id: 3,
    src: 'images/advertising/uber_eats_ad.png',
    alt: 'Uber Eats Ad',
    brand: 'Uber Eats',
    desc: "'Uber your eats'",
    date: 'Published/Aired: October 2021',
    award_title: 'Integrated Brand Campaign',
    award: 'Promax Winner',
  },
  {
    id: 5,
    src: 'images/advertising/asics_ad.png',
    alt: 'Asics Ad',
    brand: 'Asics',
    desc: 'Go on a run',
    date: 'Published/Aired: February 2015',
    award_title: 'Fashion, Beauty & Lifestyle Advertising, Media & PR 2021',
    award: 'Clio Award',
  },

  {
    id: 5,
    src: 'images/advertising/kfc_ad.png',
    alt: 'KFC Ad',
    brand: 'KFC',
    desc: "'The Secret is Experience'",
    date: 'Published/Aired: June 2021',
    award_title: 'Restaurants 2021',
    award: 'Effie Gold Award Winner',
  },

  {
    id: 3,
    src: 'images/advertising/mcdonalds_ad.png',
    alt: 'McDonalds Ad',
    brand: 'McDonalds',
    desc: "'Feel the Sound of Speed'",
    date: 'Published/Aired: December 2020',
    award_title: 'Specialty Advertising Campaign',
    award: 'Clio Award',
  },
];
